### ISSUE TITLE
Turning device (TSP800II) off/on can result in crash with following error:

### ISSUE THREAD

**Issue by linkrd** [opentable/star-printing#4]
*** Terminating app due to uncaught exception 'PortException', reason: 'Native GetParsedStatusEx failed'
*** First throw call stack:
(0x284880d7 0x36d03c77 0x108e37 0x4e4d9 0x4c72d 0x291b2439 0x2911d0a1 0x2910fb0d 0x291b4d93 0x398d89 0x392ac5 0x39ab1b 0x39be21 0x37415d9d 0x37415af0)
libc++abi.dylib: terminating with uncaught exception of type PortException

**Comment by linkrd** [comment]
Fixed:

In Printer.m add try/catch to - (void) updateStatus 

- (void)updateStatus
{
    if (![self performCompatibilityCheck]) {
        return;
    }
    PrinterStatus status = PrinterStatusNoStatus;
    @try {
        
        StarPrinterStatus_2 printerStatus;
        [self.port getParsedStatus:&printerStatus :2];
        
        if(printerStatus.offline == SM_TRUE) {
            if(printerStatus.coverOpen == SM_TRUE) {
                status = PrinterStatusCoverOpen;
            } else if(printerStatus.receiptPaperEmpty == SM_TRUE) {
                status = PrinterStatusOutOfPaper;
            } else if(printerStatus.receiptPaperNearEmptyInner == SM_TRUE ||
                      printerStatus.receiptPaperNearEmptyOuter == SM_TRUE) {
                status = PrinterStatusLowPaper;
            }
        }
        
        // CoverOpen, LowPaper, or OutOfPaper
        if(status != PrinterStatusNoStatus) {
            self.status = status;
            return;
        }
        
        // Printer did have error, but error is now resolved
        if(self.hasError) {
            self.status = self.previousOnlineStatus;
        }
    }
    @catch (PortException *e)
    {
        self.status = status;
        return;
    }
}

**Comment by teriu** [comment]
Hmm - getting this one too, the Try/Catch doesn't seem to fix it, as leads to a bunch of deallocation errors instead. Any idea why `GetParsedStatusEx` is failing?
